Import('*')

Source('timing_tree.cc')
Source('tree.cc')
Source('util.cc')

DebugFlag('IntegrityTree')
DebugFlag('TimingTree')
DebugFlag('TimingTreeInit')

PySource('gem5.components.memory.mtree',
    '__init__.py')
PySource('gem5.components.memory.mtree',
    'TimingTree.py')
